### ISSUE TITLE
Documentation is gone.

### ISSUE THREAD

**Issue by Raynos** [uber/ringpop#107]
:(

**Comment by kriskowal** [comment]
By way of https://github.com/uber/ringpop/pull/106

**Comment by jwolski** [comment]
It'll be back. Just needs a kind of reboot.

**Comment by jwolski** [comment]
The old documentation now resides in the Ringpop (Github) wiki. The wiki itself is soon to undergo a major overhaul, but I've retained the old information in the meantime.
