### ISSUE TITLE
the request proxy needs to timeout.

### ISSUE THREAD

**Issue by Raynos** [uber/ringpop#28]
`RequestProxy.handleRequest` needs to timeout and clean itself up.

Having looked at heapsnapshots too much I have a feeling that we are leaking the mock responses.

We should time them out and tear them down. I think it causes a closure leak in tchannel.

cc @jwolski

**Comment by jwolski** [comment]
Thanks, Jake. Will take care of this

**Comment by jwolski** [comment]
closing out
