### ISSUE TITLE
benchmark convergence time and other metrics

### ISSUE THREAD

**Issue by mrhooray** [uber/ringpop#36]
It would be good to benchmark convergence time and other metrics that we care.

It may not necessarily reflect the real situation in production but it can be used to have a rough idea on performance characteristics and as a baseline to prevent regression under difference scenarios that we can simulate.

The benchmark should be automated under different ringpop/swim configurations and scenarios like single node failure, catastrophic failure, parallel restart, rolling restart, capacity increase, packet loss, latency increase, etc.

I made a simple prototype under https://github.com/mrhooray/swim-js/tree/master/bench which measures convergence time under single node failure scenario. It does not include much automation but can be tuned with cli arguments and produces result like
```
configuration:
- cycles 20
- workers 30
- codec msgpack
- dissemination factor 15
- interval 20 ms
- join timeout 100 ms
- ping timeout 4 ms
- ping req timeout 12 ms
- ping req group size 3
- max dgram size 512 bytes
convergence time under single node failure
histogram data:
- count 20
- min 94
- max 198
- mean 130.4
- median 126
- variance 807.8315789473684
- std dev 28.422378136731773
- p75 143.75
- p95 196.74999999999997
- p99 198
```

Is this something we'd like to have? suggestions/ideas? @jwolski @Raynos

**Comment by jwolski** [comment]
Yes. This is much desired.

**Comment by jwolski** [comment]
this has been merged
