### ISSUE TITLE
Why parse the body instead of stream? 

### ISSUE THREAD

**Issue by indexzero** [uber/ringpop#47]
Neat thing @mranney @Raynos! I was [reading the code](https://github.com/uber/ringpop/blob/master/lib/request-proxy.js#L98-L124) and I was wondering why you read the `body` instead of streaming? 

My guess was because the use-case it was to optimize the 80% web application use-case for sending tiny amounts of `JSON` or `msgpack`, but wanted to hear from the horse's mouth :horse: :horse_racing:

**Comment by Raynos** [comment]
@indexzero For simplicity we wanted to implement a subset of HTTP for our proxying need.

We have an internal HTTP framework that does not support streaming. It was easier to verify correctness if we just parsed the entire HTTP request.

We will actually deprecate proxying HTTP over ringpop+tchannel in the future and instead support forwarding tchannel messages over ringpop.

There are other technical reasons for body parsing. Our body parsing library has an internal cache. If you are trying to shared an incoming HTTP request over ringpop and need to read the body to compute the shard key, you would have to parse it before passing it to ringpop. This means ringpop either needs to be given the body to send or use a body parsing library with a build in cache. We choose the latter.

**Comment by indexzero** [comment]
Thanks @Raynos that makes a lot of sense. I saw the cache in `body` when I was reading that code too.
