### ISSUE TITLE
tchannel v2 frame size limit

### ISSUE THREAD

**Issue by jwolski** [uber/ringpop#49]
tchannel v2 has a 65k frame size limit. full syncs and some membership update exchanges may exceed this.

**Comment by mranney** [comment]
While the frame size is 64k, the tchannel library should support transparently fragmenting a larger message into as many frames as necessary.

**Comment by jwolski** [comment]
iirc @Raynos mentioned that he observed membership state exchanges that may have exceeded the limit. however, for clusters of the size we have out in the wild now over 64k is hard to believe.

@mranney good to know that fragmented messages will cover us when we reach this point even though we should address payloads of that size before we get there.

**Comment by mrhooray** [comment]
@Raynos what's the size of cluster when you noticed full sync data size exceeds the limit?

in my experiments, membership update consists of host string, incarnation number, status number and optional meta data is around 40 to 80 bytes in buffer length with msgpack or json encoding.

we could also use a message parsing protocol over single tchannel frame to support primitive message(ping, ack, pingreq, update, sync), compound message, encrypted message, etc and receiver parses incoming data and dispatch to different message handlers(reply to ping, handle pingreq, handle udpate, etc)

i implemented above protocol over udp datagram with 512 bytes limit and it takes about on average 4~6 protocol period to achieve convergence in a cluster with 50 nodes

with 65k frame size and piggybacking updates, every ping, ack, pingreq, is roughly a full sync for a cluster with 600 to 1k nodes

**Comment by Raynos** [comment]
@mrhooray 

I was running integration tests with clusters as big as a 1000 nodes.

We will run into that limit at some point in production. We wont run into it anytime soon.

**Comment by jcorbin** [comment]
@mranney yes the library should support fragmentation transparently someday, that day isn't today, the current v2.0.0-alpha1 doesn't... issue here: https://github.com/uber/tchannel/issues/123

**Comment by charliezhang** [comment]
What's the status on this? we are already running clusters with over 1000 nodes.

**Comment by Raynos** [comment]
v2.0.0 supports fragmentation transparently.

Everything will just work.

**Comment by jwolski** [comment]
@charliezhang, is there a particular concern other than future concerns? Ringpop is only running on v2 on the tchannel v2.0.0 feature branch. When it's finally merged in, Ringpop will be released under 10.x.x

**Comment by charliezhang** [comment]
based on what @Raynos says this shouldn't be a concern anymore.

**Comment by jcorbin** [comment]
Yes, the released v2.0.0 tchannel does support fragmentation transparently, there is no effective limit from a consumer's point of view.
