### ISSUE TITLE
zalgo.

### ISSUE THREAD

**Issue by Raynos** [uber/ringpop#7]
All callbacks must be asynchronous.

```js
function createRingpop(callback) {
  var r = Ringpop({ ... })

  r.bootstrap(callback)

  return r;
}

var r = createRingpop(function (err) {
  if (err) {
    // do stuff with r
    // OOPS ZALGO. callback called before return.
  }
})
```

If we do not call callbacks in the nextTick we get horrible race conditions.

**Comment by jwolski** [comment]
closing. please reopen if you have more specific cases. just to eliminate long-standing issues.
